services:
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uppound
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./up-pound-backend
    networks:
      - app-network
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/uppound
    ports:
      - "3002:3001"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./up-pound-backend/images:/app/images

  frontend:
    build: ./up-pound-frontend-new
    networks:
      - app-network
    environment:
      REACT_APP_API_URL: http://localhost:3002
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
